version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage:
    name: deploy
    displayName: 部署
    steps:
      - step: publish@general_artifacts
        name: publish_static_files
        displayName: 上传静态文件
        artifacts:
          - name: STATIC_FILES
            path:
              - index.html
              - img/
        artifactName: static-output
triggers:
  pr:
    branches:
      include:
        - master
